Сделал первую страницу
htmlacademy-htmlcss/1981775-sedona-33 pull request #2
Opened 2022-01-25 12:42 UTC by Alexanderrrrrrrrrrr

2022-01-31 11:50 UTC, baronin requested changes

2022-01-31 11:50 UTC, baronin commented on index.html
> +      <h2 class="visually-hidden"></h2>
Тут должно быть описание секции

2022-01-31 11:50 UTC, baronin commented on index.html
> +
соблюдай пожалуйста отступы, что бы было единообразно

2022-01-31 11:50 UTC, baronin commented on index.html
> +          <img class="logo" src="" alt="Логотип седона">
Логотип находится отдельно от ссылки на "Главная"

2022-01-31 11:50 UTC, baronin commented on index.html
> +          <a class="navigation-link" href="#">Гостиница</a>
В макете вместо "Гостиница" => "Хочу сюда!"

2022-01-31 11:50 UTC, baronin commented on index.html
> +      <p class="main-foto">welcome</p>
В макете это сделано картинкой,  пока что p p и h1 лишние 

![image](https://user-images.githubusercontent.com/20131942/151786388-c7229d41-f98d-4a4c-96ea-2d1e54b7c494.png)

2022-01-31 11:50 UTC, baronin commented on index.html
> +        <li>Жилье Рекомендуем пожить в нвстоящем мотеле,всё как в кино</li>
![image](https://user-images.githubusercontent.com/20131942/151786882-ea7e7c04-8bae-4163-8e17-4175f56071fd.png)
тут получается идет 
img картинка
h3 заголовок
p текс

2022-01-31 11:50 UTC, baronin commented on index.html
> +        <li><img src="#"></li>
пожалуйста, поставь всем img => alt
![image](https://user-images.githubusercontent.com/20131942/151787172-4e63ffb6-82f3-4723-9a52-2bedc44b05d1.png)

2022-01-31 11:50 UTC, baronin commented on index.html
> +      <h3>Заинтересовались</h3>
тут больше подходить h2

2022-01-31 11:50 UTC, baronin commented on index.html
> +        <a href="http://htmlacademy.ru/"></a>
Сначала телефон идет потом логотип ) 
и они не находятся в списке, в списке только социальные сети

2022-02-01 09:56 UTC, Alexanderrrrrrrrrrr commented on index.html
> +      <h3>Заинтересовались</h3>
не могу найти где вообще слово заинтересовались

2022-02-01 10:05 UTC, Alexanderrrrrrrrrrr commented on index.html
> +          <img class="logo" src="" alt="Логотип седона">
не понятно что нужно сделать

2022-02-08 19:15 UTC, merged